<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rémy Lachelin">
<meta name="author" content="Chhavi Sachdeva">
<meta name="author" content="Nicolas Rothen">
<meta name="keywords" content="Sequence space synaesthesia, Synaesthesia/synesthesia, consistency test, space, time, numbers">
<meta name="description" content="SPACE-SEQUENCE SYNESTHESIA: OPTIMIZING CONSISTENCY TESTS">

<title>Pre-registered report: Mapping Synesthetic Sequences in Space: Improving Consistency Test by Harnessing Cartography Tools.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="2.RegisteredReport_MS2_files/libs/clipboard/clipboard.min.js"></script>
<script src="2.RegisteredReport_MS2_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="2.RegisteredReport_MS2_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="2.RegisteredReport_MS2_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="2.RegisteredReport_MS2_files/libs/quarto-html/popper.min.js"></script>
<script src="2.RegisteredReport_MS2_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="2.RegisteredReport_MS2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2.RegisteredReport_MS2_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2.RegisteredReport_MS2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2.RegisteredReport_MS2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2.RegisteredReport_MS2_files/libs/bootstrap/bootstrap-396162e8ef7d12afffc1aaca992ac734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="_extensions/wjschne/apaquarto/apa.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-introduction" id="toc-sec-introduction" class="nav-link active" data-scroll-target="#sec-introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#sec-consistency-tests" id="toc-sec-consistency-tests" class="nav-link" data-scroll-target="#sec-consistency-tests">Consistency tests</a></li>
  <li><a href="#present-study" id="toc-present-study" class="nav-link" data-scroll-target="#present-study">Present study</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#datasets-and-participants" id="toc-datasets-and-participants" class="nav-link" data-scroll-target="#datasets-and-participants"><em>Datasets and Participants</em></a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">Procedure</a></li>
  <li><a href="#analyses" id="toc-analyses" class="nav-link" data-scroll-target="#analyses">Analyses</a>
  <ul class="collapse">
  <li><a href="#consistency-tests-on-the-stimulus-level" id="toc-consistency-tests-on-the-stimulus-level" class="nav-link" data-scroll-target="#consistency-tests-on-the-stimulus-level">Consistency tests on the <em>stimulus level</em></a></li>
  <li><a href="#consistency-tests-on-the-space-form-level" id="toc-consistency-tests-on-the-space-form-level" class="nav-link" data-scroll-target="#consistency-tests-on-the-space-form-level">Consistency tests on the <em>space-form level</em></a></li>
  <li><a href="#receiver-operator-characteristic-analyses" id="toc-receiver-operator-characteristic-analyses" class="nav-link" data-scroll-target="#receiver-operator-characteristic-analyses">Receiver Operator Characteristic analyses</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#sec-results" id="toc-sec-results" class="nav-link" data-scroll-target="#sec-results">Results</a>
  <ul class="collapse">
  <li><a href="#roc-analyses" id="toc-roc-analyses" class="nav-link" data-scroll-target="#roc-analyses">ROC analyses</a></li>
  <li><a href="#further-analyses" id="toc-further-analyses" class="nav-link" data-scroll-target="#further-analyses">Further analyses</a></li>
  </ul></li>
  <li><a href="#sec-phase-ii-methods" id="toc-sec-phase-ii-methods" class="nav-link" data-scroll-target="#sec-phase-ii-methods">Methods - future study</a></li>
  <li><a href="#discussion---present-study" id="toc-discussion---present-study" class="nav-link" data-scroll-target="#discussion---present-study">Discussion - present study</a>
  <ul class="collapse">
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations">Limitations</a></li>
  <li><a href="#topological-validity" id="toc-topological-validity" class="nav-link" data-scroll-target="#topological-validity">Topological validity</a></li>
  <li><a href="#sec-conclusions" id="toc-sec-conclusions" class="nav-link" data-scroll-target="#sec-conclusions">Intermediary Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a>
  <ul class="collapse">
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a></li>
  </ul></li>
  <li>Appendix A</li>
  <li><a href="#apx-featDensity" id="toc-apx-featDensity" class="nav-link" data-scroll-target="#apx-featDensity">Test’s distributions</a></li>
  <li>Appendix B</li>
  <li><a href="#apx-SM2byds" id="toc-apx-SM2byds" class="nav-link" data-scroll-target="#apx-SM2byds">ROC analysis by dataset</a></li>
  <li>Appendix C</li>
  <li><a href="#apx-byquestperc" id="toc-apx-byquestperc" class="nav-link" data-scroll-target="#apx-byquestperc">ROC Analysis Sub-sampled data by questionnaire quantiles (20% steps)</a></li>
  <li>Appendix D</li>
  <li><a href="#apx-correlation-with-self-report" id="toc-apx-correlation-with-self-report" class="nav-link" data-scroll-target="#apx-correlation-with-self-report">Correlation with self-report</a></li>
  <li>Appendix E</li>
  <li><a href="#apx-average-forms" id="toc-apx-average-forms" class="nav-link" data-scroll-target="#apx-average-forms">Centred average forms</a></li>
  <li>Appendix F</li>
  <li><a href="#apx-alluvial" id="toc-apx-alluvial" class="nav-link" data-scroll-target="#apx-alluvial">Alluvial plot</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">




<br>

<br>

<section id="title" class="level1 title unnumbered unlisted">
<h1 class="title unnumbered unlisted">Pre-registered report: Mapping Synesthetic Sequences in Space: Improving Consistency Test by Harnessing Cartography Tools.</h1>
<div class="Author">
<br>

<p>Rémy Lachelin, Chhavi Sachdeva, and Nicolas Rothen</p>
<p>Psychology, UniDistance Suisse</p>
</div>
<br>

<br>

</section>
<section id="author-note" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Author Note</h1>
<p>Rémy Lachelin <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orchid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> <a href="https://orcid.org/0000-0002-8485-7153">https://orcid.org/0000-0002-8485-7153</a></p>
<p>Chhavi Sachdeva <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orchid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> <a href="https://orcid.org/0000-0002-0074-4371">https://orcid.org/0000-0002-0074-4371</a></p>
<p>Nicolas Rothen <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orchid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> <a href="https://orcid.org/0000-0002-8874-8341">https://orcid.org/0000-0002-8874-8341</a></p>
<p>Author roles were classified using the Contributor Role Taxonomy (CRediT; https://credit.niso.org/) as follows: <em>Rémy Lachelin</em><strong>: </strong>conceptualization, methodology, formal analysis, data curation, and Writing - Original Draft. <em>Chhavi Sachdeva</em><strong>: </strong>conceptualization, methodology, and Writing - Review &amp; Editing. <em>Nicolas Rothen</em><strong>: </strong>conceptualization, Writing - Review &amp; Editing, supervision, project administration, and Founding Acquisition</p>
<p>Correspondence concerning this article should be addressed to Rémy Lachelin, Psychology, UniDistance Suisse, Schinerstrasse 18, Brig-Glis, Valais 3900, Email: <a href="mailto:remy.lachelin@fernuni.ch">remy.lachelin@fernuni.ch</a></p>
<br>
</section>
<section id="abstract" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Abstract</h1>
<div class="AbstractFirstParagraph">
<p>Sequence-space synesthesia is a perceptual condition in which ordinal sequences (e.g., numbers, days of the week, or months of the year) are experienced as occupying specific spatial locations. This perceptual condition is identified using self-reports (e.g.&nbsp;questionnaires) and behavioural consistency tasks. Existing consistency tests measure the spatial distance between responses to repeated stimuli, but they ignore the ordinal and geometric features of spatial-forms. This preregistered study consists of a present and future analyses. In the present analyses, we optimise SSS diagnostics from consistency test by extracting novel geometric features at the spatial-form level. To do this, we first evaluate classification performances of old and new features in a large (N = 685) aggregated sample from four available and independent datasets. We then harness a geographic toolbox to extract metrics from the spatial-forms level. Finally, receiver operating characteristic (ROC) analyses are conducted to assess the discriminative performances of each method. The results show that permuted topological validity of spatial-forms and the perimeter between stimuli performs equally well in detecting SSS. In a future study, we will examine predictive validity of the selected methods on an independent dataset that has yet to be collected. Findings from the present study highlight the relevance of topological principles for sequence-space representations and aims to optimise the ability of consistency tests to detect SSS.</p>
</div>
<p><em>Keywords</em>: Sequence space synaesthesia, Synaesthesia/synesthesia, consistency test, space, time, numbers</p>
<br>
</section>
<section id="firstheader" class="level1 title unnumbered unlisted">
<h1 class="title unnumbered unlisted">Pre-registered report: Mapping Synesthetic Sequences in Space: Improving Consistency Test by Harnessing Cartography Tools.</h1>
</section>
<section id="sec-introduction" class="level1">
<h1>Introduction</h1>
<p>Sequence-Space Synaesthesia (SSS) or visuo-spatial forms is the phenomenon where people visualize ordered sequences in particular spatial positions. For example, numbers, weekdays or months (synesthetic <em>inducers</em>) are represented as arranged into specific spatial positions in space (synesthetic <em>concurrent</em>). The synaesthetic spatial-forms can be complex and have variable geometric forms. Those geometric forms might be different for each categories (i.e.&nbsp;number-forms weekdays and months), with forms such as ellipses, zig-zags or curbed lines <span class="citation" data-cites="galton1880">Flournoy (<a href="#ref-flournoy1893" role="doc-biblioref">1893</a>)</span>. SSS are usually identified using questionnaires and consistency tests. An individual is identified as SSS based on the variability at the stimulus level between repeated responses: less variable responses being an indicator of the consistent response characteristic of SSS. However, stimulus level consistency can also be achieved by responding to the same position for all stimuli. Furthermore, it might favour linear over circular spatial-forms and is not informed about the ordinality between stimuli (e.g.&nbsp;1 <code>→</code> 2 <code>→</code> 3, etc.). Here, we aim at optimizing the identification of SSS from consistency tasks using geometrical characteristics of spatial-forms from ordered stimuli or inducers.</p>
<p>SSS frequently co-occurs with other subtypes of synaesthesia and as for other subtypes of synaesthesia it’s idiosyncratic. Colour-grapheme synaesthesia, where a grapheme <em>inducer</em> triggers a <em>concurrent</em> colour (i.e.&nbsp;“A” seen as red), co-occurs at 71 % to 76 % with SSS <span class="citation" data-cites="sagiv2006">(<a href="#ref-sagiv2006" role="doc-biblioref">Sagiv et al., 2006</a>)</span>. Nevertheless, across different synaesthetic subtypes, self-reported SSS tend to cluster together <span class="citation" data-cites="ward2022">(<a href="#ref-ward2022" role="doc-biblioref">Ward &amp; Simner, 2022</a>)</span>, indicating a degree of internal homogeneity and justifying to study it as a distinct phenomenon. Spatial-forms are idiosyncratic, which results in considerable heterogeneity in how this phenomenon is manifested across individuals. One source of heterogeneity is given by dimensionality: some SSS experiences can involve three-dimensional (3D) and two-dimensional (2D) arrangements <span class="citation" data-cites="eagleman2009a price2013">(<a href="#ref-eagleman2009a" role="doc-biblioref">Eagleman, 2009</a>; <a href="#ref-price2013" role="doc-biblioref">Price &amp; Pearson, 2013</a>)</span>. Another source of heterogeneity is the reference frame, for example, the spatial-forms might take place in an external space around the body (<em>i.e.</em> projector) or in an egocentric internal space (<em>i.e.</em> associator) <span class="citation" data-cites="dixon2004 smilek2007">(<a href="#ref-dixon2004" role="doc-biblioref">Dixon et al., 2004</a>; <a href="#ref-smilek2007" role="doc-biblioref">Smilek et al., 2007</a>)</span>. Further variability can be explained by temporal-spatial properties and mental-manipulation of spatial-forms such as “zooming” in and out or rotating or shifting perspectives at will <span class="citation" data-cites="gould2014 jarick2009">(<a href="#ref-gould2014" role="doc-biblioref">Gould et al., 2014</a>; <a href="#ref-jarick2009" role="doc-biblioref">Jarick et al., 2009</a>)</span> Lastly, the shape, complexity and layout of the spatial-forms are also heterogeneous such as forming for example ovals, lines, zig-zags or loops. With some recurring shapes being more frequent across SSS, such as ovals for months <span class="citation" data-cites="eagleman2009a">(<a href="#ref-eagleman2009a" role="doc-biblioref">Eagleman, 2009</a>)</span>.</p>
<p>Despite the after mentioned heterogeneities, SSS is also phenomenological characterized. There might be five main characteristics for synaesthesia in general and specifically SSS <span class="citation" data-cites="seron1992 deroy2013">(<a href="#ref-deroy2013" role="doc-biblioref">Deroy &amp; Spence, 2013</a>; <a href="#ref-seron1992" role="doc-biblioref">Seron et al., 1992</a>)</span>. <em>Automaticity</em>: the inducer automatically triggers the concurrent. <em>Unidirectionality</em>: while the <em>inducer</em> triggers the concurrent, the concurrent does not trigger the inducer. <em>Developmentally</em>: the experience was already present during childhood. <em>Consciousness</em>: The concurrent is consciously perceived. <em>Consistency</em>: the inducer-concurrent pair remains stable in time within subject. While some of these characteristics can be captured with self-reported questionnaire (i.e.&nbsp;for development and consciousness), other can be quantified more objectively using behavioural tasks such as consistency tests <span class="citation" data-cites="baron-cohen1993">(<a href="#ref-baron-cohen1993" role="doc-biblioref">Baron-Cohen et al., 1993</a>)</span>.</p>
<section id="sec-consistency-tests" class="level2">
<h2 data-anchor-id="sec-consistency-tests">Consistency tests</h2>
<p>Consistency tests are extracted form behavioural tasks used to evaluate how stable synesthetic experiences are over time <span class="citation" data-cites="rothen2013a rothen2016">(<a href="#ref-rothen2013a" role="doc-biblioref">Rothen et al., 2013</a>, <a href="#ref-rothen2016" role="doc-biblioref">2016</a>)</span>. They do this by presenting the same stimuli repeatedly and assessing how similar participant’s responses are across repetitions (i.e.&nbsp;<em>inducer</em>-<em>concurrent</em> associations). High consistency is often taken as evidence for synaesthesia. Consistency tests have proven effective for colour-grapheme synaesthesia. Measures of individual consistency can be derived using colour pickers while repeatedly presenting the same inducer (i.e.&nbsp;“A”). The quantification of the distance between concurrents from the same inducers is used to discriminate consistent synaesthetes from controls. Specifically, the euclidean distance in CIE L*u*v colour space, which is designed for perceptual uniformity, yields optimal classification accuracy when using a cut-off estimated as deduced from a larger representative sample <span class="citation" data-cites="rothen2013a">(<a href="#ref-rothen2013a" role="doc-biblioref">Rothen et al., 2013</a>)</span>. A similar rationale to that used for colour-grapheme synaesthesia has been applied to characterize SSS from consistency tasks.</p>
<p>In the SSS consistency task, participants complete multiple rounds of the same stimuli (e.g., digits, days of the week, and months of the year) and are asked to indicate a spatial location for each stimulus by clicking on the computer screen. <span class="citation" data-cites="brang2010">Brang et al. (<a href="#ref-brang2010" role="doc-biblioref">2010</a>)</span> for example evaluated consistency as the distance between repeated responses to the same inducer or stimuli (e.g.&nbsp;January and January) relative to adjacent stimuli (e.g.&nbsp;February). A response was defined as consistent if it fell within 1.96 <em>z-scores</em>. However, this criterion was noted to be potentially too conservatory, as it identified synaesthesia in 4 of 81 self-reported synaesthetes. Geometrical features such as area and perimeter between the coordinates of repeated inducers have further been used as a measure of the distance between same inducers, hence as a metric for consistency. Less consistent responses leading to smaller triangle perimeters and area <span class="citation" data-cites="rothen2016">(<a href="#ref-rothen2016" role="doc-biblioref">Rothen et al., 2016</a>)</span>. A cut-off corresponding to less than 0.203 % average responses area in proportion to the total screen area to classify as SSS has been suggested <span class="citation" data-cites="ward2018">(see also <a href="#ref-ward2018" role="doc-biblioref">Ward et al., 2018</a>)</span>.</p>
<p>However, several general caveats of consistency tests using concurrent or stimulus level metrics have been identified. Some tests may favour certain spatial-forms <span class="citation" data-cites="ward2018">(<a href="#ref-ward2018" role="doc-biblioref">Ward et al., 2018</a>)</span> in particular those with linear or highly regular spatial layouts, i.e.&nbsp;elliptical patterns for months<span class="citation" data-cites="flournoy1893 eagleman2009a brang2010">(<a href="#ref-brang2010" role="doc-biblioref">Brang et al., 2010</a>; <a href="#ref-eagleman2009a" role="doc-biblioref">Eagleman, 2009</a>; <a href="#ref-flournoy1893" role="doc-biblioref">Flournoy, 1893</a>)</span>. Another concern is that participants that respond with the same position, for example when not knowing the response, will have artificially high consistencies with those metrics <span class="citation" data-cites="rothen2016">(<a href="#ref-rothen2016" role="doc-biblioref">Rothen et al., 2016</a>)</span>. This has led to alternative approaches such as to add the standard deviation of responses, questionnaire cut-off <span class="citation" data-cites="ward2018">(<a href="#ref-ward2018" role="doc-biblioref">Ward et al., 2018</a>)</span> or permutation-based comparison of individual responses to chance levels for colour-grapheme <span class="citation" data-cites="root2021">(<a href="#ref-root2021" role="doc-biblioref">Root et al., 2021</a>)</span> and SSS <span class="citation" data-cites="ward2022a">(<a href="#ref-ward2022a" role="doc-biblioref">Ward, 2022</a>)</span>. Finally, these consistency tests evaluate the variability of responses to the same stimuli, therefore the ordinality between stimuli is not taken into account. Synaesthetic spatial-forms follow ordinal rules (e.g.&nbsp;Monday <code>→</code> Tuesday <code>→</code> Wednesday). In the domain of numerical cognition, ordinality has been identified as an important information when processing sequences <span class="citation" data-cites="lyons2013">(<a href="#ref-lyons2013" role="doc-biblioref">Lyons &amp; Beilock, 2013</a>)</span>. Some studies of SSS have systematically investigated ordinality by investigating metrics of adjacent inducer-concurrent pairs such as distances <span class="citation" data-cites="brang2010">(<a href="#ref-brang2010" role="doc-biblioref">Brang et al., 2010</a>)</span> or angles <span class="citation" data-cites="eagleman2009a">(<a href="#ref-eagleman2009a" role="doc-biblioref">Eagleman, 2009</a>)</span>. However, ordinality of the concurrent spatial-form might be particularly relevant considering all the stimuli of a certain category (i.e.&nbsp;weekdays or months). The spatial-forms of the concurrents are often spatially structured into configuration such as lines or polygons that may follow distinctive geometrical rules. For example linear layouts have been described in early accounts of number forms <span class="citation" data-cites="flournoy1893 galton1880">(<a href="#ref-flournoy1893" role="doc-biblioref">Flournoy, 1893</a>; <a href="#ref-galton1880" role="doc-biblioref">Galton, 1880</a>)</span>.</p>
</section>
<section id="present-study" class="level2">
<h2 data-anchor-id="present-study">Present study</h2>
<p>The goal of this registered report is to compare different consistency tests on their classification performances of individuals with SSS and controls doing the consistency task using Receiver Operator Characteristics (ROC) analyses. In the present <em>Phase I</em>, we merge four previously available datasets using the same task on both SSS and control groups <span class="citation" data-cites="ward2022a">(<a href="#ref-ward2022a" role="doc-biblioref">Ward, 2022</a>)</span>. First, we aimed to reproduce established consistency test methods based on stimulus-level consistency metrics, such as area and perimeter. Second, we explored a new approach comparing geometrical features across repetitions of the same categories (weekday, month and numbers), such as segments and polygons. These novel tests are designed to take advantage of the sequentiality or ordinality between the responses and the geometrical properties at the spatial-form level, see <a href="#fig-myplot00" class="quarto-xref" aria-expanded="false">Figure&nbsp;2</a>. All the consistency tests are then compared using ROC analyses on their correct classification performances of self-reported SSS and control groups.</p>
<p>In a future study, we will assess whether the tests identified in the present study generalize and are validated on an independent dataset that is yet to be acquired (<span class="citation" data-cites="sachdeva2024">Sachdeva et al. (<a href="#ref-sachdeva2024" role="doc-biblioref">2024</a>)</span>, Stage 1 in-principle acceptance, see also <a href="https://osf.io/6wn4m" class="uri">https://osf.io/6wn4m</a>).</p>
</section>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<p>Code and data for “one-click” reproducibility of this manuscript including the following analyses are available on git-hub (<a href="https://github.com/remLach/SpaceSequenceSynDiagnostic" class="uri">https://github.com/remLach/SpaceSequenceSynDiagnostic</a>). All the analyses are conducted in R, using the following packages ‘pROC’ v. 1.19.0.1 <span class="citation" data-cites="pROC">(<a href="#ref-pROC" role="doc-biblioref">Robin et al., 2011</a>)</span>, ‘sf’ v. 1.0.21 <span class="citation" data-cites="sf">(<a href="#ref-sf" role="doc-biblioref">Pebesma &amp; Bivand, 2023</a>)</span> and for visualization ‘ggplot2’ v. 4.0.1 <span class="citation" data-cites="ggplot2">(<a href="#ref-ggplot2" role="doc-biblioref">Wickham, 2016</a>)</span>, ‘ggVennDiagram’ v. 1.5.6 <span class="citation" data-cites="ggVennDiagram">(<a href="#ref-ggVennDiagram" role="doc-biblioref">Gao &amp; Dusa, 2025</a>)</span>.</p>
<section id="datasets-and-participants" class="level2">
<h2 data-anchor-id="datasets-and-participants"><em>Datasets and Participants</em></h2>
<p>To base the optimization of the consistency test on the largest possible sample we looked for accessible datasets that used the same consistency tasks on groups of synesthetes and controls. We found four datasets that met these criteria. Two datasets were collected in laboratory settings <span class="citation" data-cites="rothen2016">Rothen et al. (<a href="#ref-rothen2016" role="doc-biblioref">2016</a>)</span> (see also <a href="https://osf.io/6hq94/files/osfstorage">https://osf.io/6hq94</a>) and <span class="citation" data-cites="vanpetersen2020">Van Petersen et al. (<a href="#ref-vanpetersen2020" role="doc-biblioref">2020</a>)</span> (see also <a href="https://data.ru.nl/collections/di/dcc/DSC_2018.00019_653" class="uri">https://data.ru.nl/collections/di/dcc/DSC_2018.00019_653</a>). The two others came from on-line testing <span class="citation" data-cites="ward2022a">Ward (<a href="#ref-ward2022a" role="doc-biblioref">2022</a>)</span> (see also<a href="https://osf.io/nu5v4" class="uri">https://osf.io/nu5v4</a>) and an additional dataset was gently provided by private communications with Professor Ward. To match the other datasets, stimuli of the weekdays and months categories were translated from Dutch to English in the dataset from <span class="citation" data-cites="vanpetersen2020">(<a href="#ref-vanpetersen2020" role="doc-biblioref">Van Petersen et al., 2020</a>)</span>. For the number category we included only digits from 0 to 9 that where presented across all datasets (i.e.&nbsp;excluding the stimuli “50” and “100” for numbers in <span class="citation" data-cites="vanpetersen2020">Van Petersen et al. (<a href="#ref-vanpetersen2020" role="doc-biblioref">2020</a>)</span>).</p>
<p>From the merged datasets, we kept 685 from the total 689 participants. First, we excluded 0.02 % empty trials (i.e.&nbsp;skipped responses) including trials flagged for having the same x or y coordinates across conditions and repetitions, causing the depletion n = 2 participants<span class="citation" data-cites="rothen2016 ward2018">(as in <a href="#ref-rothen2016" role="doc-biblioref">Rothen et al., 2016</a>; <a href="#ref-ward2018" role="doc-biblioref">Ward et al., 2018</a>)</span>. n = 2 participants were excluded for having less than 4 coordinate points since polygons need at least four coordinate. Note therefore, that 31 participants of the final sample did not have responses in all three conditions X repetition cases. From the final sample of N = 685, 396 were synaesthetes and 289 controls, see <a href="#tbl-mytable01" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a> and <a href="#tbl-mytable02" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a>.</p>
<div id="tbl-mytable01" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" prefix="" data-tblnum="1" data-apa-note="Synesthetes. Demographics were not provided in the dataset Ward 2. Before: before participant exclusion" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mytable01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Synesthetes</p>
</div>
</figcaption>
<div aria-describedby="tbl-mytable01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-mytable01" class="caption-top table" prefix="" data-tblnum="1">
<thead>
<tr class="header">
<th>Synaesthetes</th>
<th>N before</th>
<th>N after</th>
<th>Age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="rothen2016">(<a href="#ref-rothen2016" role="doc-biblioref">Rothen et al., 2016</a>)</span></td>
<td>33</td>
<td>32</td>
<td>23.1</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="vanpetersen2020">(<a href="#ref-vanpetersen2020" role="doc-biblioref">Van Petersen et al., 2020</a>)</span></td>
<td>23</td>
<td>22</td>
<td>23.2</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="ward2022a">(<a href="#ref-ward2022a" role="doc-biblioref">Ward, 2022</a>)</span></td>
<td>252</td>
<td>252</td>
<td>37.2</td>
</tr>
<tr class="even">
<td>Ward 2</td>
<td>90</td>
<td>90</td>
<td>NA</td>
</tr>
<tr class="odd">
<td>Total:</td>
<td>398</td>
<td>396</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Synesthetes.&nbsp;Demographics were not provided in the dataset Ward 2. Before: before participant exclusion
</div>
</div>
<div id="tbl-mytable02" class="quarto-float quarto-figure quarto-figure-center FigureWithNote" prefix="" data-tblnum="2" data-apa-note="Controls. Demographics were not provided in the dataset Ward 2. Before: before participant exclusion" data-custom-style="FigureWithNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mytable02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Controls</p>
</div>
</figcaption>
<div aria-describedby="tbl-mytable02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-mytable02" class="caption-top table" prefix="" data-tblnum="2">
<thead>
<tr class="header">
<th>Controls</th>
<th>N before</th>
<th>N after</th>
<th>Age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="rothen2016">(<a href="#ref-rothen2016" role="doc-biblioref">Rothen et al., 2016</a>)</span></td>
<td>37</td>
<td>37</td>
<td>28.2</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="vanpetersen2020">(<a href="#ref-vanpetersen2020" role="doc-biblioref">Van Petersen et al., 2020</a>)</span></td>
<td>21</td>
<td>21</td>
<td>21.6</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="ward2022a">(<a href="#ref-ward2022a" role="doc-biblioref">Ward, 2022</a>)</span></td>
<td>215</td>
<td>213</td>
<td>19.9</td>
</tr>
<tr class="even">
<td>Ward 2</td>
<td>18</td>
<td>18</td>
<td>NA</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>291</td>
<td>289</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Controls.&nbsp;Demographics were not provided in the dataset Ward 2. Before: before participant exclusion
</div>
</div>
<p>Regarding the synaesthets profiles, detailed participant information such as questionnaire responses were only available from the two datasets from the data by Professor Ward (i.e.&nbsp;a majority of 573 participants). We described the self-reported profiles for the stimulus categories used in the consistency test (i.e.&nbsp;number, weekdays and month), see <a href="#fig-myplot01" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a>. From this Venn-diagram we see that 240 of the SSS report having spatial-forms for Numbers, Days and Month; 42 only Days and Month; 21 only Number and Day. Also, 127 controls report spatial-forms for either Days, Numbers, Months or combinations.</p>
<div class="cell FigureWithNote" data-apa-note="Only data from Pr. Ward is represented here. SSS = Sequence-space synaesthesia" data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-myplot01" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplot01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Venn diagram of the types of self-reported SSS</p>
</div>
</figcaption>
<div aria-describedby="fig-myplot01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplot01-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Only&nbsp;data from Pr. Ward is represented here. SSS = Sequence-space synaesthesia
</div>
</div>
</section>
<section id="procedure" class="level2">
<h2 data-anchor-id="procedure">Procedure</h2>
<p>For the consistency task, each stimuli were presented randomly and sequentially centrally on the screen. Participant were instructed to click on the screen position where they visualize them. In <span class="citation" data-cites="vanpetersen2020">Van Petersen et al. (<a href="#ref-vanpetersen2020" role="doc-biblioref">2020</a>)</span> and <span class="citation" data-cites="rothen2016">Rothen et al. (<a href="#ref-rothen2016" role="doc-biblioref">2016</a>)</span> the participants were allowed to skip responses.</p>
<p>Stimulus included here were 7 weekdays (Monday to Sunday), 12 months (January to December) and 9 numbers (0 to 9). For all the data from Professor Ward the stimuli were presented in randomized order with the constraint that no stimulus was repeated until all unique stimuli (N = 29) had been presented once. The median display resolution was 1440 X 768, with a maximum of 2560 X 2025 and a minimum of 308 X 149.</p>
</section>
<section id="analyses" class="level2">
<h2 data-anchor-id="analyses">Analyses</h2>
<section id="consistency-tests-on-the-stimulus-level" class="level3">
<h3 data-anchor-id="consistency-tests-on-the-stimulus-level">Consistency tests on the <em>stimulus level</em></h3>
<p>We reproduced the tests extracted from consistency tasks found in the literature such as area and perimeter between repetitions <span class="citation" data-cites="rothen2016 ward2022a vanpetersen2020">(<a href="#ref-rothen2016" role="doc-biblioref">Rothen et al., 2016</a>; <a href="#ref-vanpetersen2020" role="doc-biblioref">Van Petersen et al., 2020</a>; <a href="#ref-ward2022a" role="doc-biblioref">Ward, 2022</a>)</span>. Formally, the area (see <a href="#eq-area" class="quarto-xref">Equation&nbsp;1</a>) and perimeter (see <a href="#eq-perim" class="quarto-xref">Equation&nbsp;2</a>) are calculated from the triangle (i.e.&nbsp;given three repetitions) formed by the <em>x</em> and <em>y</em> coordinates of the three repetitions of each stimuli (i.e.&nbsp;<em>(x1, y1), (x2, y2), (x3, y3)</em>).</p>
<p><span id="eq-area"><span class="math display">
Area = \frac{|x1y2 +x2y3 + x3y1 – x1y3 – x2y1 – x3y2|}{2}
\tag{1}</span></span></p>
<p><span id="eq-perim"><span class="math display">
Perimeter = \sqrt{(x2 - x1)^2 + (y2 – y1)^2} + \sqrt{(x3 - x2)^2 + (y3 –y2)^2} + \sqrt{(x1 - x3)^2 + (y1 – y3)^2}
\tag{2}</span></span></p>
<p>Each stimuli’s area was then averaged by participants. The area metric is in % of the screen area to be able to compare with the consistency across studies using different screen sizes. To account for screen size and spread variability across the datasets and participants, area and perimeter were also calculated on individually normalized x and y coordinates (<em>z-score</em>). These methods compute consistency metrics at the stimulus level, the rationale is that consistent responses would show less variability between repetitions. For example, smaller area or perimeter of the triangle formed indicate more variability hence more consistent responses between the three repetitions.</p>
<!--#
# Excluded this method because it is chronophage, does not work well (i.e. ROC). 

### Permuted consistency

Higher-order analytical methods such as permutation-based methods were
also used as metrics. We reproduced @root2021 permutation test for
colour-grapheme synaesthesia and adapted it to SSS as in @ward2022a. For
each individual, the x and y coordinates were randomly permuted and the
areas were calculated. After 1000 permutations per individual, a z-score
was calculated with the observed means compared to the permuted
distribution [@eq-zsPermRoot]. The distribution of the permuted results
form an individual chance level distribution, hence the z-score reflects
where the observed area lies on the chance level distribution.

$$
Zscore = \frac{(Observed) – (Mean Permuted)}{(SD Permuted)}
$$ {#eq-zsPermRoot}

The rationale is that synaesthetes consistencies should be closer (?).
 I think I would exclude this one. The permutation was originally used setting an arbitrary threshold -->
</section>
<section id="consistency-tests-on-the-space-form-level" class="level3">
<h3 data-anchor-id="consistency-tests-on-the-space-form-level">Consistency tests on the <em>space-form level</em></h3>
<p>For the novel consistency tests, we extracted geometrical features at the spatial-form level for each repetition separately. Taking the stimuli as an ordered sequence we can consider them as a geometrical segments (i.e.&nbsp;open geometrical form) and polygons (i.e.&nbsp;closed geometrical form), similarly as originally described in <span class="citation" data-cites="galton1880">Galton (<a href="#ref-galton1880" role="doc-biblioref">1880</a>)</span>.</p>
<p>We harnessed a geospatial analysis, the ‘sf’ package version 1.0.21 <span class="citation" data-cites="sf">(<a href="#ref-sf" role="doc-biblioref">Pebesma &amp; Bivand, 2023</a>)</span> to extract polyons and geometry-based features from participant’s 2D (x,y) coordinate responses. This package allows, for example, to build and analyse segments or polygons and then extract multiple geometrical descriptors or features. Informed by the ordinality of the stimulus, we defined segments and polygon by conditions and repetitions. The rationale here was to determine whether, when considering the spatial-forms formed by stimuli as ordered coordinates (i.e.&nbsp;as segments or polygon) they remain consistent <em>between</em> repetitions for each individuals. We extracted the topological validity, topological simplicity and a compactness score for each polygons (i.e.&nbsp;3 conditions X 3 repetitions: 9 polygons per participants.</p>
<section id="segment-self-intersections" class="level4">
<h4 data-anchor-id="segment-self-intersections">Segment self-intersections.</h4>
<p>The first consistency test extracted from the segments is self-intersection. We considered the spatial-forms as a segment constituted by the lines connecting consecutive stimuli separately for each category and repetitions (i.e.&nbsp;Monday (repetition 1) <code>→</code> Tuesday (repetition 1) <code>→</code> Wednesday (repetition 1), ect) and then counted the number of times each segment self-intersect. The rationale is that SSS should have less chance to produce that self-intersect than control. The number of self-intersections were computed separately for each repetitions and conditions and averaged per participants.</p>
</section>
<section id="topological-validity-and-simplicity" class="level4">
<h4 data-anchor-id="topological-validity-and-simplicity">Topological validity and simplicity.</h4>
<p>We assessed topological validity using geometric validation test. Topological validity tests if a polygons is well-formed and valid according to the Open Geospatial Consortium (OGC) Simple Features Specification <span class="citation" data-cites="herring2010">(<a href="#ref-herring2010" role="doc-biblioref">Herring, 2010</a>)</span>. A polygon is considered topologically valid if it satisfies the following criteria: (1) if polygon rings are simple (i.e., they do not touch or self-intersect), (2) boundary rings to not cross (3) boundary rings may only touch points tangentially (4) rings that define holes are contained within the exterior ring (5) the polygon rings must not splits the polygon <span class="citation" data-cites="postgis">(<a href="#ref-postgis" role="doc-biblioref"><em>PostGIS 3.6.2dev Manual</em>, n.d.</a>)</span>. Topological simplicity evaluates whether a geometric object has a simple structure without self-intersections or self-tangencies. According to the OGC Simple Features Specification <span class="citation" data-cites="herring2010">(<a href="#ref-herring2010" role="doc-biblioref">Herring, 2010</a>)</span>, a polygon boundary is considered simple if it does not pass through the same point more than once <span class="citation" data-cites="postgis">(<a href="#ref-postgis" role="doc-biblioref"><em>PostGIS 3.6.2dev Manual</em>, n.d.</a>)</span>. For polygons, simplicity requires that each ring does not self-intersect or self-touch. Note that simplicity is a condition for validity: a polygon can be simple but still invalid (e.g., if an interior ring extends outside the exterior ring).</p>
<p>For each participant we tested for topological validity and simplicity across individual 3 categories (weekdays, month and numbers) and 3 repetitions, hence 9 space-forms or polygons. The binary outcome (1 = is valid, 0 = invalid) was then averaged across all 9 forms. Hence, it can span from 1 (all 9 are valid/simple) to 0 (none of the 9 forms are valid/simple). Thus, the topological validity and simplicity score ranges from 0 (none of the nine polygons are valid/simple) to 1 (all nine polygons are valid). For example, if a participant’s polygon for weekdays were valid across all three repetitions, months were valid in two of three repetitions, and numbers were invalid in all repetitions, the topological validity score would be 5/9 ≈ 0.56.</p>
</section>
<section id="compactness-score" class="level4">
<h4 data-anchor-id="compactness-score">Compactness score.</h4>
<p>We also implemented a measure of compactness for the polygons. We used the score developed to quantify the gerrymandering of political district by <span class="citation" data-cites="polsby1991">Polsby and Popper (<a href="#ref-polsby1991" role="doc-biblioref">1991</a>)</span>. Gerrymandering is a politically motivated strategy of redefining district’s boundary to give the advantage to a political party. This has the consequences to reduce the compactness of those districts as would be expected if they where defined from geomorphology. The compactness is calculated as the ratio of the area and perimeter of a polygon. The rationale is that more compact forms (i.e.&nbsp;higher Polsby–Popper scores) would be more likely in SSS than controls. Formally, the Polsby–Popper score is calculated from the polygon’s area and perimeter <a href="#eq-PP" class="quarto-xref">Equation&nbsp;3</a>:</p>
<p><span id="eq-PP"><span class="math display">
score = \frac{4\pi \cdot Area}{Perimeter^2}
\tag{3}</span></span></p>
</section>
<section id="permutation-based-feature-extraction" class="level4">
<h4 data-anchor-id="permutation-based-feature-extraction">Permutation-based feature extraction.</h4>
<p>Finally, we implemented permutations of the repetition order to derive a permuted measure of consistency. Specifically, instead of using repetitions in chronological order, we shuffled the repetition order between stimulus presentation (i.e.&nbsp;Monday (repetition 2) <code>→</code> Tuesday (repetition 3) <code>→</code> Wednesday (repetition 1), ect) and extracted the geometrical feature from x,y coordinates of same stimulus categories in non-chronological order The form-based tests computed before were relying on the chronologically ordered repetitions. For example, when a stimulus such as Monday was repeated three times, the coordinates for the first presentation of Monday were always paired with the coordinates for the first presentation of Tuesday to construct segments or polygons. However, if synesthetic forms are truly consistent, they should remain stable independently of the chronological order of stimulus presentation. Hence, we permute the repetitions within each condition. Specifically, for each participant and each category, we randomized the response repetition order. For example segments for weekdays were constructed with the x,y coordinates where randomly permuted across repetition order, for example Monday (repetition 1), Tuesday (repetition 3), Wednesday (repetition 2), ect. We predicted that this permuted-based consistency would yield to better classification performance (higher AUC values) compared to chronologically ordered features. The rationale is that genuine synaesthetes would have a consistently valid topology of spatial-forms repetitions regardless of presentation order, whereas controls would show random variation. The permutation scores were calculated for topological validity and Polsby–Popper score.</p>
</section>
</section>
<section id="receiver-operator-characteristic-analyses" class="level3">
<h3 data-anchor-id="receiver-operator-characteristic-analyses">Receiver Operator Characteristic analyses</h3>
<p>Each of the previous method’s performance in classifying SSS from controls was compared with Receiver Operator Characteristics (ROC) analyses. Classification performance was quantified using the area under the curve (AUC), with higher AUC values indicating better discrimination between SSS and control groups. The optimal cutoffs were calculated using Youden’s index<span class="citation" data-cites="youden1950">(<a href="#ref-youden1950" role="doc-biblioref">Youden, 1950</a>)</span>. Discriminant Power (DP) was used as an additional estimate of discrimination performance according to the optimal cutoff (<a href="#eq-DP" class="quarto-xref">Equation&nbsp;4</a>). DP around 1 being interpreted as inefficient discrimination.</p>
<p><span id="eq-DP"><span class="math display">
DP = \frac{\sqrt{3}}{\pi} (\log(\frac{sensitivity}{1−sensitivity}) + \log(\frac{specificity}{(1−specificity)}))  
\tag{4}</span></span></p>
<p>The statistical comparison of ROC curves between the methods was operated testing the difference of AUC between pairs of curves using bootstrapping method (1000 times) since it allows to compare methods with different directions. Each bootstrap results in the subtraction of the AUC between the two ROC. Then the each of the AUC difference’s (D) are divided by the standard deviation of those difference and compared to a normal distribution (<a href="#eq-D" class="quarto-xref">Equation&nbsp;5</a>).</p>
<p><span id="eq-D"><span class="math display">
D = \frac{AUC_1-AUC_2}{SD}
\tag{5}</span></span></p>
<p>Therefore we statistically compared all the AUC of each methods as the difference to the highest AUC method.</p>
<div class="cell FigureWithNote" data-apa-note="Example participant for months" data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-myplot00" class="quarto-float quarto-figure quarto-figure-center" prefix="" data-fignum="2" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplot00-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Design for novel method for consistency test: from between trial varibility to Segment and polygons formed by the space-forms using geography tools.</p>
</div>
</figcaption>
<div aria-describedby="fig-myplot00-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplot00-1.png" class="img-fluid figure-img" data-fig-pos="H" width="1950">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Example&nbsp;participant for months
</div>
</div>
</section>
</section>
</section>
<section id="sec-results" class="level1">
<h1>Results</h1>
<div class="cell FigureWithNote" data-apa-note="Grey line indicates chance level" data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-myplot2" class="quarto-float quarto-figure quarto-figure-center" data-fignum="3" prefix="">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Receiver Operating Characteristic (ROC) curves of all tests</p>
</div>
</figcaption>
<div aria-describedby="fig-myplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplot2-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Grey&nbsp;line indicates chance level
</div>
</div>
<div class="cell FigureWithoutNote" data-ft.align="left" prefix="" data-tblnum="3" data-custom-style="FigureWithoutNote">
<div id="tbl-mytb03" class="cell quarto-float quarto-figure quarto-figure-center" prefix="" data-tblnum="3" data-ft.align="left">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mytb03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>ROC analyses of all tests</p>
</div>
</figcaption>
<div aria-describedby="tbl-mytb03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 43%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Feature</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">DP</th>
<th style="text-align: right;">threshold</th>
<th style="text-align: right;">sensitivity</th>
<th style="text-align: right;">specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">Permuted valid structure [boolean/9]</td>
<td style="text-align: right;">81.16</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">70.78</td>
<td style="text-align: right;">78.55</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">Polsby–Popper [score/9]</td>
<td style="text-align: right;">78.89</td>
<td style="text-align: right;">2.29</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">59.70</td>
<td style="text-align: right;">87.54</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Perimeter [z-score]</td>
<td style="text-align: right;">78.80</td>
<td style="text-align: right;">2.06</td>
<td style="text-align: right;">1.73</td>
<td style="text-align: right;">72.54</td>
<td style="text-align: right;">75.78</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">Valid structure [boolean/9]</td>
<td style="text-align: right;">78.12</td>
<td style="text-align: right;">1.90</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">72.80</td>
<td style="text-align: right;">72.32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">Permuted P-P [score/9]</td>
<td style="text-align: right;">77.15</td>
<td style="text-align: right;">2.46</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">57.18</td>
<td style="text-align: right;">90.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Segment self-intersections [n/9]</td>
<td style="text-align: right;">72.93</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">79.85</td>
<td style="text-align: right;">60.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Area of the polygon [z-score]</td>
<td style="text-align: right;">72.03</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">64.99</td>
<td style="text-align: right;">68.51</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Simple topology [boolean/9]</td>
<td style="text-align: right;">69.74</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">61.96</td>
<td style="text-align: right;">68.51</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Area [z-score]</td>
<td style="text-align: right;">69.27</td>
<td style="text-align: right;">1.68</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">76.32</td>
<td style="text-align: right;">63.32</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Perimeter of the polygon [z-score]</td>
<td style="text-align: right;">59.12</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">10.46</td>
<td style="text-align: right;">83.88</td>
<td style="text-align: right;">41.87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Perimeter [screen size %]</td>
<td style="text-align: right;">55.34</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">76.07</td>
<td style="text-align: right;">38.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Area [screen size %]</td>
<td style="text-align: right;">50.87</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">76.83</td>
<td style="text-align: right;">40.48</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell FigureWithoutNote" data-ft.align="left" data-apa-notes="Mean (Standart Deviation) of all the consistency tests" prefix="" data-tblnum="4" data-custom-style="FigureWithoutNote">
<div id="tbl-mytb04" class="cell quarto-float quarto-figure quarto-figure-center" data-apa-notes="Mean (Standart Deviation) of all the consistency tests" data-ft.align="left" data-tblnum="4" prefix="">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mytb04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Descriptives of each test</p>
</div>
</figcaption>
<div aria-describedby="tbl-mytb04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 42%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: left;">Control</th>
<th style="text-align: left;">SSS</th>
<th style="text-align: left;">Control [zs]</th>
<th style="text-align: left;">SSS [zs]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Permuted valid structure [boolean/9]</td>
<td style="text-align: left;">0.12 (0.16)</td>
<td style="text-align: left;">0.36 (0.25)</td>
<td style="text-align: left;">-0.57 (0.64)</td>
<td style="text-align: left;">0.41 (1.01)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Polsby–Popper [score/9]</td>
<td style="text-align: left;">0.11 (0.13)</td>
<td style="text-align: left;">0.27 (0.19)</td>
<td style="text-align: left;">-0.51 (0.69)</td>
<td style="text-align: left;">0.37 (1.03)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Perimeter [z-score]</td>
<td style="text-align: left;">3.30 (1.72)</td>
<td style="text-align: left;">1.59 (1.16)</td>
<td style="text-align: left;">0.60 (1.04)</td>
<td style="text-align: left;">-0.44 (0.70)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Valid structure [boolean/9]</td>
<td style="text-align: left;">0.13 (0.19)</td>
<td style="text-align: left;">0.39 (0.28)</td>
<td style="text-align: left;">-0.54 (0.69)</td>
<td style="text-align: left;">0.39 (1.01)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Permuted P-P [score/9]</td>
<td style="text-align: left;">0.11 (0.17)</td>
<td style="text-align: left;">0.41 (0.33)</td>
<td style="text-align: left;">-0.56 (0.56)</td>
<td style="text-align: left;">0.40 (1.06)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Segment self-intersections [n/9]</td>
<td style="text-align: left;">9.56 (11.31)</td>
<td style="text-align: left;">1.87 (5.42)</td>
<td style="text-align: left;">0.48 (1.23)</td>
<td style="text-align: left;">-0.35 (0.59)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Area of the polygon [z-score]</td>
<td style="text-align: left;">1.00 (0.99)</td>
<td style="text-align: left;">1.91 (1.31)</td>
<td style="text-align: left;">-0.42 (0.79)</td>
<td style="text-align: left;">0.30 (1.03)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simple topology [boolean/9]</td>
<td style="text-align: left;">0.22 (0.23)</td>
<td style="text-align: left;">0.40 (0.27)</td>
<td style="text-align: left;">-0.39 (0.85)</td>
<td style="text-align: left;">0.28 (1.01)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Area [z-score]</td>
<td style="text-align: left;">0.26 (0.32)</td>
<td style="text-align: left;">0.08 (0.14)</td>
<td style="text-align: left;">0.42 (1.29)</td>
<td style="text-align: left;">-0.30 (0.55)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perimeter of the polygon [z-score]</td>
<td style="text-align: left;">9.49 (3.44)</td>
<td style="text-align: left;">8.39 (2.48)</td>
<td style="text-align: left;">0.21 (1.16)</td>
<td style="text-align: left;">-0.16 (0.83)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Perimeter [screen size %]</td>
<td style="text-align: left;">0.03 (0.03)</td>
<td style="text-align: left;">0.03 (0.08)</td>
<td style="text-align: left;">0.03 (0.44)</td>
<td style="text-align: left;">-0.02 (1.26)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Area [screen size %]</td>
<td style="text-align: left;">0.46 (0.87)</td>
<td style="text-align: left;">0.26 (0.52)</td>
<td style="text-align: left;">0.17 (1.25)</td>
<td style="text-align: left;">-0.12 (0.75)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>Descriptively, the triangle area (in % screen size) between repetition for SSS was surprisingly larger than in previous studies: 0.26% (<em>SD = 0.52%</em>) compared to 0.15% (<em>SD = 0.13 %</em>) in <span class="citation" data-cites="rothen2016">Rothen et al. (<a href="#ref-rothen2016" role="doc-biblioref">2016</a>)</span> and 0.14 % (<em>SD = 0.17</em>) % in <span class="citation" data-cites="ward2018">Ward et al. (<a href="#ref-ward2018" role="doc-biblioref">2018</a>)</span>, see <a href="#tbl-mytb04" class="quarto-xref" aria-expanded="false">Table&nbsp;4</a>. These values also differ between the available datasets (See <a href="#fig-apx08" class="quarto-xref" aria-expanded="false">Figure&nbsp;B2</a>). However, those differences could be mitigated by using individually standardized coordinates, see <a href="#tbl-mytb04" class="quarto-xref" aria-expanded="false">Table&nbsp;4</a>.</p>
</div>
<section id="roc-analyses" class="level2">
<h2 data-anchor-id="roc-analyses">ROC analyses</h2>
<p>All ROC were compared to the permuted validity method, since it led the highest AUC (81.16), all p-values false discovery rate (FDR) adjusted. ROC analyses are summarized in <a href="#tbl-mytb03" class="quarto-xref" aria-expanded="false">Table&nbsp;3</a> and <a href="#fig-myplot2" class="quarto-xref" aria-expanded="false">Figure&nbsp;3</a>. Interestingly, while the permuted validity leads to significantly larger AUC than the Polsby-Popper method, (<em>D</em> = 2.12 , <em>p</em> &lt; .05, it led to similar AUC than the standardized perimeter (<em>D</em> = 1.39, <em>p</em> &lt; .05). This might be explained by the relatively lower sensitivity 59.7 (although relatively higher sensitivity 87.54) of the Polsby-Popper test compared to the Perimeter (72.54) and permuted validity tests (70.78). Additionally, the permuted validity led to significantly higher AUC than the non permuted one (D = 3.07, <em>p</em> &lt; .05).</p>
<p>Hence, the two best AUC performances are from the averaged permuted validity score (AUC = 81.16; DP = 2.13, cut-off = 0.17 corresponding to 1.53 valid of 9 forms) and the standardized perimeter between the repetitions of each stimuli (AUC = 78.8; DP = 2.06, cut-off = 1.73 z-scores). At the proposed cut-off, the permuted validity leads to higher specificity than perimeter (78.55 vs. 75.78) indicating better rejection of controls (i.e.&nbsp;less false negatives), but lower sensitivity (70.78 vs. 72.54), indicating poorer detection of SSS (i.e.&nbsp;more false negatives).</p>
<p>In sum, the permuted validity on the space-form level and the perimeter of standardized coordinates on the stimulus level were the two equally optimal tests to classify controls and SSS.</p>
</section>
<section id="further-analyses" class="level2">
<h2 data-anchor-id="further-analyses">Further analyses</h2>
<p>We conducted further analyses by subsampling the dataset source and questionnaire percentiles. The aim of these analyses was to test the stability of the classifications from different methods across experiments (i.e.&nbsp;datasets) and sample characteristics (i.e. questionnaire scores). We also used a correlational approach to test for correlations between features and questionnaires.</p>
<p>We sub-sampled the dataset source for the five most optimal tests (i.e. higher AUC) and recalculated AUC, sensitivity and sensibility. We found similar values for the different datasets, see <a href="#fig-myplotapx02" class="quarto-xref" aria-expanded="false">Figure&nbsp;B1</a>.</p>
<p>Including only the data by Professor Ward, we subsampled the participants depending on the perecntiles of the questionnaire scores (hence only the data from Professor Ward), taking the 10-0% highest questionnaire scores against the 10 % lowest (. (i.e.&nbsp;90-100 %). Here also most of the values remain relatively stable independently from the questionnaire distribution of the samples, see <a href="#fig-myplotapx03" class="quarto-xref" aria-expanded="false">Figure&nbsp;C1</a>. Another important point addressed in the literature about consistency test is circularity. The circularity is given in that if consistency tests are used to classify SSS and controls, then those groups will by definition differ in consistency <span class="citation" data-cites="root2025">(<a href="#ref-root2025" role="doc-biblioref">Root et al., 2025</a>)</span>. Hence, we made a correlation matrix with the questionnaire scores and all the tests, see Appendix. The two highest correlations are indeed between the questionnaire score and perimeter (r = .58) and permuted validity (r = .50), see <a href="#fig-myplotapx04" class="quarto-xref" aria-expanded="false">Figure&nbsp;D1</a>.</p>
<p>Some of the participants might have been originally mis-attributed to control or SSS or there might be consistent controls and inconsistent synesthetes <span class="citation" data-cites="root2025 eagleman2007">(<a href="#ref-eagleman2007" role="doc-biblioref">Eagleman et al., 2007</a>; see <a href="#ref-root2025" role="doc-biblioref">Root et al., 2025</a>)</span>. We found about ~6 % of the full sample’s synesthetes to be consistently classified as controls (i.e.&nbsp;consistent false positive) by the five methods with the highest AUC, see , see <a href="#fig-myplotapx07" class="quarto-xref" aria-expanded="false">Figure&nbsp;F1</a> and <a href="#fig-myplotapx08" class="quarto-xref" aria-expanded="false">Figure&nbsp;F2</a>. ~3 % controls are consistently classified as SSS (i.e.&nbsp;consistent false negative) <a href="#fig-myplotapx09" class="quarto-xref" aria-expanded="false">Figure&nbsp;F3</a>.</p>
<p>Finally, we also wanted to visualize the average space form of each category at the population level to see if there were qualitative differences between the forms. The figure in the appendix (<a href="#fig-myplotapx06" class="quarto-xref" aria-expanded="false">Figure&nbsp;E1</a>), shows more circular patterns for months and more linear horizontal and vertical for numbers.</p>
</section>
</section>
<section id="sec-phase-ii-methods" class="level1">
<h1>Methods - future study</h1>
<p>Additional data will be collected in the future using the same consistency test, with the procedural exception that there will be four repetitions per stimuli instead of three ( <span class="citation" data-cites="sachdeva2024">Sachdeva et al. (<a href="#ref-sachdeva2024" role="doc-biblioref">2024</a>)</span>, Stage 1 in-principle acceptance). Hence for the stimulus levels tests we will compare the area and perimeter of a quadrilateral of four coordinates pairs instead of a triangle. Materials are more details on this study are pre-registered on OSF, including ample size and recruitment method <span class="citation" data-cites="sachdeva2024">(<a href="#ref-sachdeva2024" role="doc-biblioref">Sachdeva et al., 2024</a>, Stage 1 in-principle acceptance)</span> (see also <a href="https://osf.io/6wn4m" class="uri">https://osf.io/6wn4m</a>).</p>
<p>We will compute the same ROC analyses as in this pre-registration on all the tests. Since we obtain different best AUC per tests depending on the dataset (see <a href="#fig-myplotapx02" class="quarto-xref" aria-expanded="false">Figure&nbsp;B1</a>) it is likely that the best test here will not match with the best test in the to be collected dataset.</p>
</section>
<section id="discussion---present-study" class="level1">
<h1>Discussion - present study</h1>
<p>Our investigation of four datasets found two main consistency tests leading to the optimal classification of SSS from control: standardized perimeter between stimulus repetitions and permuted topological validity on the space-form level.</p>
<p>Further analyses show variabilities between the test’s AUC exists depending on the dataset source, which could explain why we could not replicate <span class="citation" data-cites="rothen2016">Rothen et al. (<a href="#ref-rothen2016" role="doc-biblioref">2016</a>)</span>’s area but rather found the perimeter as a more optimal test. The stability across varying percentiles of the synesthesia questionnaire’s score suggest the tests work as well for more marked forms of SSS (note however that this analysis was limited Professor Ward’s data). The standardized perimeter also leads to slightly higher correlation with the questionnaire scores (r = .57) than permuted topological validity (r = .51), see <a href="#fig-myplotapx04" class="quarto-xref" aria-expanded="false">Figure&nbsp;D1</a>.</p>
<p>In sum, while we could prove similar performances using a different approach based on the space-form level (i.e.&nbsp;topological validity), we found similar classification performances than using stimulus-repetition level test such as perimeter.</p>
<section id="sec-limitations" class="level2">
<h2 data-anchor-id="sec-limitations">Limitations</h2>
<p>Although an optimal test to classify SSS might be particularly relevant for experimental purposes, several important limitations need to be considered. First, consistency tests contain only a limited set of sequential stimuli (i.e.&nbsp;months, weeks and the first ten natural numbers) that could potentially elicit synaesthetic experiences. Other ordinal categories such as temperature, clock time, musical keys might be more relevant for some individuals with SSS. For numbers specifically, better consistency tests might be obtained using a larger set size (i.e.&nbsp;including decades and hundreds), as descriptively interesting form changes occur at different decimals in base-10 number systems <span class="citation" data-cites="galton1880">(<a href="#ref-galton1880" role="doc-biblioref">Galton, 1880</a>)</span>.</p>
<p>Second, the use of diagnostic cutoffs assumes categorical distinctions between groups, but SSS may exist on a continuum and scores might be more suitable <span class="citation" data-cites="price2013">(<a href="#ref-price2013" role="doc-biblioref">Price &amp; Pearson, 2013</a>)</span>. This limitation is related to the circularity mentioned previously: diagnostic cutoffs as calculated here depend on how SSS and controls are classified in the first place <span class="citation" data-cites="simner2012">(<a href="#ref-simner2012" role="doc-biblioref">Simner, 2012</a>)</span>. Measures of other characteristics of synaesthesia such as automaticity or visual Gabor detection might be necessary to establish external validity <span class="citation" data-cites="ward2018">(<a href="#ref-ward2018" role="doc-biblioref">Ward et al., 2018</a>)</span>. Indeed, determining the prevalence of SSS in the general population requires definitional choices that might be based on more conservative or lenient criteria <span class="citation" data-cites="jonas2014 brang2010 sagiv2006 ward2018">(<a href="#ref-brang2010" role="doc-biblioref">Brang et al., 2010</a>; <a href="#ref-jonas2014" role="doc-biblioref">Jonas &amp; Price, 2014</a>; <a href="#ref-sagiv2006" role="doc-biblioref">Sagiv et al., 2006</a>; <a href="#ref-ward2018" role="doc-biblioref">Ward et al., 2018</a>)</span>. These difficulties are reflected in the span of current prevalence estimates of SSS: 4.4 % <span class="citation" data-cites="brang2013">(<a href="#ref-brang2013" role="doc-biblioref">Brang et al., 2013</a>)</span>, 8.1 % <span class="citation" data-cites="ward2018">(<a href="#ref-ward2018" role="doc-biblioref">Ward et al., 2018</a>)</span> and 14 % <span class="citation" data-cites="seron1992">(<a href="#ref-seron1992" role="doc-biblioref">Seron et al., 1992</a>)</span>.</p>
<p>Third, as shown in <a href="#fig-myplotapx02" class="quarto-xref" aria-expanded="false">Figure&nbsp;B1</a>, we find that the optimal criteria can vary across datasets. In other word, we obtain different AUC depending on the datasets. These differences might be explained by different sampling methods biases, for example <span class="citation" data-cites="vanpetersen2020">(<a href="#ref-vanpetersen2020" role="doc-biblioref">Van Petersen et al., 2020</a>)</span> recruited SSS from over one hundred candidates to maximise participant reporting synesthetic experiences.</p>
<!--#  Another possible explanation may be methodological and related to the option to skip responses in the task, leaving empty cases for some participants. Indeed, having fewer responses (i.e., fewer coordinates) increases the likelihood of producing a valid spatial form also in controls. Conversely, perimeter and area are differentially affected by missing responses. It is also possible that SSS are not actually inconsistent [@root2025; @eagleman2007] or that non self-reported SSS are consistent [@itoh2024]. Another possibility might have to do with the original classification of SSS. Indeed 55 % (127 of 231) of the controls from the data provided by Pr. Ward, report at least a space-form for Number Day or Month, see @fig-myplot1. Therefore some controls might also give consistent responses. Sequence-space associations could also be learned or memorized, leading to high consistency in non-synaesthetes as found for colour-grapheme [@ovallefresa2019].  -->
</section>
<section id="topological-validity" class="level2">
<h2 data-anchor-id="topological-validity">Topological validity</h2>
<p>Surprisingly, permuted topological validity of the spatial-forms led to similar results than the perimeter test. This novel result might be informative about how SSS map ordinal stimuli in space. Indeed, it seems the patterns of spatial-forms follow topological rules analogous to geographical and geometry-based space structures. Analogies between maps and neuroscience have a long history <span class="citation" data-cites="eagleman2009">(i.e.&nbsp;retinotopy, sonotopy or somatotopy <a href="#ref-eagleman2009" role="doc-biblioref">Eagleman &amp; Goodale, 2009</a>)</span>. Therefore spatial-forms might originate from the mapping between ordinal or sequential stimuli on idiosyncratic visuo-spatial abilities following topological rules. One of the advantages of using topological validity is that it also classifies responses with the same coordinates as invalid and hence inconsistent, while using the area and perimeter metrics they would qualify as highly consistent responses.</p>
<!--#  Interestingly, ordinality is a very important semantic property of numbers, one of the categories used for SSS [@lyons2013]. Numbers are acquired sequentially (i.e. 1 →  2 →  3, ect. [@gelman1978] which would fit developmental accounts of the acquisition of SSS [@price2013].  -->
</section>
<section id="sec-conclusions" class="level2">
<h2 data-anchor-id="sec-conclusions">Intermediary Conclusion</h2>
<p>The present study compared traditional stimulus-level consistency tests with novel form-level geometric tests for detecting SSS. We found optimal classification performance from permuted topological validity and standardized perimeter between repetitions. Despite not yielding to better classification than stimulus level methods, this new method is theoretically meaningful since genuine synesthetes should produce more compact and topologically valid structures compared to controls. Similarly, the perimeter test captures the stability of the overall spatial configuration across repetitions, which should remain consistent for true SSS individuals regardless of presentation order.</p>
<p>In the future study, we will attempt at validating these criteria on a yet-to be acquired dataset.</p>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-baron-cohen1993" class="csl-entry" role="listitem">
Baron-Cohen, S., Harrison, J., Goldstein, L. H., &amp; Wyke, M. (1993). Coloured Speech Perception: Is Synaesthesia what Happens when Modularity Breaks Down? <em>Perception</em>, <em>22</em>(4), 419–426. <a href="https://doi.org/10.1068/p220419">https://doi.org/10.1068/p220419</a>
</div>
<div id="ref-brang2013" class="csl-entry" role="listitem">
Brang, D., Miller, L. E., McQuire, M., Ramachandran, V. S., &amp; Coulson, S. (2013). Enhanced mental rotation ability in time-space synesthesia. <em>Cognitive Processing</em>, <em>14</em>(4), 429–434. <a href="https://doi.org/10.1007/s10339-013-0561-5">https://doi.org/10.1007/s10339-013-0561-5</a>
</div>
<div id="ref-brang2010" class="csl-entry" role="listitem">
Brang, D., Teuscher, U., Ramachandran, V. S., &amp; Coulson, S. (2010). Temporal sequences, synesthetic mappings, and cultural biases: The geography of time. <em>Consciousness and Cognition</em>, <em>19</em>(1), 311–320. <a href="https://doi.org/10.1016/j.concog.2010.01.003">https://doi.org/10.1016/j.concog.2010.01.003</a>
</div>
<div id="ref-ggalluvial" class="csl-entry" role="listitem">
Brunson, J. C., &amp; Read, Q. D. (2023). <em><span class="nocase">ggalluvial</span>: Alluvial plots in ’ggplot2’</em>. <a href="http://corybrunson.github.io/ggalluvial/">http://corybrunson.github.io/ggalluvial/</a>
</div>
<div id="ref-deroy2013" class="csl-entry" role="listitem">
Deroy, O., &amp; Spence, C. (2013). Why we are not all synesthetes (not even weakly so). <em>Psychonomic Bulletin &amp; Review</em>, <em>20</em>(4), 643–664. <a href="https://doi.org/10.3758/s13423-013-0387-2">https://doi.org/10.3758/s13423-013-0387-2</a>
</div>
<div id="ref-dixon2004" class="csl-entry" role="listitem">
Dixon, M. J., Smilek, D., &amp; Merikle, P. M. (2004). Not all synaesthetes are created equal: Projector versus associator synaesthetes. <em>Cognitive, Affective, &amp; Behavioral Neuroscience</em>, <em>4</em>(3), 335–343. <a href="https://doi.org/10.3758/CABN.4.3.335">https://doi.org/10.3758/CABN.4.3.335</a>
</div>
<div id="ref-eagleman2009a" class="csl-entry" role="listitem">
Eagleman, D. M. (2009). The objectification of overlearned sequences: A new view of spatial sequence synesthesia. <em>Cortex</em>, <em>45</em>(10), 1266–1277. <a href="https://doi.org/10.1016/j.cortex.2009.06.012">https://doi.org/10.1016/j.cortex.2009.06.012</a>
</div>
<div id="ref-eagleman2009" class="csl-entry" role="listitem">
Eagleman, D. M., &amp; Goodale, M. A. (2009). Why color synesthesia involves more than color. <em>Trends in Cognitive Sciences</em>, <em>13</em>(7), 288–292. <a href="https://doi.org/10.1016/j.tics.2009.03.009">https://doi.org/10.1016/j.tics.2009.03.009</a>
</div>
<div id="ref-eagleman2007" class="csl-entry" role="listitem">
Eagleman, D. M., Kagan, A. D., Nelson, S. S., Sagaram, D., &amp; Sarma, A. K. (2007). A standardized test battery for the study of synesthesia. <em>Journal of Neuroscience Methods</em>, <em>159</em>(1), 139–145. <a href="https://doi.org/10.1016/j.jneumeth.2006.07.012">https://doi.org/10.1016/j.jneumeth.2006.07.012</a>
</div>
<div id="ref-flournoy1893" class="csl-entry" role="listitem">
Flournoy, T. (1893). <em>Des phénomènes de synopsie (audition colorée): Photismes, schèmes visuels, personnifications</em>. Alcan. <a href="https://books.google.bj/books?id=JISQxpcyGUMC">https://books.google.bj/books?id=JISQxpcyGUMC</a>
</div>
<div id="ref-galton1880" class="csl-entry" role="listitem">
Galton, F. (1880). Visualised Numerals. <em>Nature</em>, <em>21</em>(533), 252–256. <a href="https://doi.org/10.1038/021252a0">https://doi.org/10.1038/021252a0</a>
</div>
<div id="ref-ggVennDiagram" class="csl-entry" role="listitem">
Gao, C.-H., &amp; Dusa, A. (2025). <em><span class="nocase">ggVennDiagram</span>: A ’ggplot2’ implement of venn diagram</em>. <a href="https://github.com/gaospecial/ggVennDiagram">https://github.com/gaospecial/ggVennDiagram</a>
</div>
<div id="ref-gould2014" class="csl-entry" role="listitem">
Gould, C., Froese, T., Barrett, A. B., Ward, J., &amp; Seth, A. K. (2014). An extended case study on the phenomenology of sequence-space synesthesia. <em>Frontiers in Human Neuroscience</em>, <em>8</em>. <a href="https://doi.org/10.3389/fnhum.2014.00433">https://doi.org/10.3389/fnhum.2014.00433</a>
</div>
<div id="ref-herring2010" class="csl-entry" role="listitem">
Herring, J. R. (2010). <em>OpenGIS® Implementation Standard for Geographic information - Simple feature access - Part 1: Common architecture</em>.
</div>
<div id="ref-jarick2009" class="csl-entry" role="listitem">
Jarick, M., Dixon, M. J., Stewart, M. T., Maxwell, E. C., &amp; Smilek, D. (2009). A different outlook on time: Visual and auditory month names elicit different mental vantage points for a time-space synaesthete. <em>Cortex</em>, <em>45</em>(10), 1217–1228. <a href="https://doi.org/10.1016/j.cortex.2009.05.014">https://doi.org/10.1016/j.cortex.2009.05.014</a>
</div>
<div id="ref-jonas2014" class="csl-entry" role="listitem">
Jonas, C. N., &amp; Price, M. C. (2014). Not all synesthetes are alike: Spatial vs. Visual dimensions of sequence-space synesthesia. <em>Frontiers in Psychology</em>, <em>5</em>. <a href="https://doi.org/10.3389/fpsyg.2014.01171">https://doi.org/10.3389/fpsyg.2014.01171</a>
</div>
<div id="ref-lyons2013" class="csl-entry" role="listitem">
Lyons, I. M., &amp; Beilock, S. L. (2013). Ordinality and the Nature of Symbolic Numbers. <em>The Journal of Neuroscience</em>, <em>33</em>(43), 17052–17061. <a href="https://doi.org/10.1523/JNEUROSCI.1775-13.2013">https://doi.org/10.1523/JNEUROSCI.1775-13.2013</a>
</div>
<div id="ref-sf" class="csl-entry" role="listitem">
Pebesma, E., &amp; Bivand, R. (2023). <em><span class="nocase">Spatial Data Science: With applications in <span>R</span></span></em>. <span>Chapman and Hall/CRC</span>. <a href="https://doi.org/10.1201/9780429459016">https://doi.org/10.1201/9780429459016</a>
</div>
<div id="ref-polsby1991" class="csl-entry" role="listitem">
Polsby, D. D., &amp; Popper, R. (1991). The Third Criterion: Compactness as a Procedural Safeguard Against Partisan Gerrymandering. <em>SSRN Electronic Journal</em>. <a href="https://doi.org/10.2139/ssrn.2936284">https://doi.org/10.2139/ssrn.2936284</a>
</div>
<div id="ref-postgis" class="csl-entry" role="listitem">
<em>PostGIS 3.6.2dev manual</em>. (n.d.).
</div>
<div id="ref-price2013" class="csl-entry" role="listitem">
Price, M., &amp; Pearson, D. (2013). Toward a visuospatial developmental account of sequence-space synesthesia. <em>Frontiers in Human Neuroscience</em>, <em>7</em>. <a href="https://doi.org/10.3389/fnhum.2013.00689">https://doi.org/10.3389/fnhum.2013.00689</a>
</div>
<div id="ref-pROC" class="csl-entry" role="listitem">
Robin, X., Turck, N., Hainard, A., Tiberti, N., Lisacek, F., Sanchez, J.-C., &amp; Müller, M. (2011). <span class="nocase">pROC</span>: An open-source package for <span>R</span> and <span>S</span>+ to analyze and compare ROC curves. <em>BMC Bioinformatics</em>, <em>12</em>, 77.
</div>
<div id="ref-root2021" class="csl-entry" role="listitem">
Root, N., Asano, M., Melero, H., Kim, C.-Y., Sidoroff-Dorso, A. V., Vatakis, A., Yokosawa, K., Ramachandran, V., &amp; Rouw, R. (2021). Do the colors of your letters depend on your language? Language-dependent and universal influences on grapheme-color synesthesia in seven languages. <em>Consciousness and Cognition</em>, <em>95</em>, 103192. <a href="https://doi.org/10.1016/j.concog.2021.103192">https://doi.org/10.1016/j.concog.2021.103192</a>
</div>
<div id="ref-root2025" class="csl-entry" role="listitem">
Root, N., Chkhaidze, A., Melero, H., Sidoroff-Dorso, A., Volberg, G., Zhang, Y., &amp; Rouw, R. (2025). How <span>“</span>diagnostic<span>”</span> criteria interact to shape synesthetic behavior: The role of self-report and test<span></span>retest consistency in synesthesia research. <em>Consciousness and Cognition</em>, <em>129</em>, 103819. <a href="https://doi.org/10.1016/j.concog.2025.103819">https://doi.org/10.1016/j.concog.2025.103819</a>
</div>
<div id="ref-rothen2016" class="csl-entry" role="listitem">
Rothen, N., Jünemann, K., Mealor, A. D., Burckhardt, V., &amp; Ward, J. (2016). The sensitivity and specificity of a diagnostic test of sequence-space synesthesia. <em>Behavior Research Methods</em>, <em>48</em>(4), 1476–1481. <a href="https://doi.org/10.3758/s13428-015-0656-2">https://doi.org/10.3758/s13428-015-0656-2</a>
</div>
<div id="ref-rothen2013a" class="csl-entry" role="listitem">
Rothen, N., Seth, A. K., Witzel, C., &amp; Ward, J. (2013). Diagnosing synaesthesia with online colour pickers: Maximising sensitivity and specificity. <em>Journal of Neuroscience Methods</em>, <em>215</em>(1), 156–160. <a href="https://doi.org/10.1016/j.jneumeth.2013.02.009">https://doi.org/10.1016/j.jneumeth.2013.02.009</a>
</div>
<div id="ref-sachdeva2024" class="csl-entry" role="listitem">
Sachdeva, C., Whelan, E., Ovalle-Fresa, R., Rey-Mermet, A., Ward, J., &amp; Rothen, N. (2024). <em>How perceptual ability shapes memory: An investigation in healthy special populations</em>. <a href="https://osf.io/6wn4m">https://osf.io/6wn4m</a>
</div>
<div id="ref-sagiv2006" class="csl-entry" role="listitem">
Sagiv, N., Simner, J., Collins, J., Butterworth, B., &amp; Ward, J. (2006). What is the relationship between synaesthesia and visuo-spatial number forms? <em>Cognition</em>, <em>101</em>(1), 114–128. <a href="https://doi.org/10.1016/j.cognition.2005.09.004">https://doi.org/10.1016/j.cognition.2005.09.004</a>
</div>
<div id="ref-seron1992" class="csl-entry" role="listitem">
Seron, X., Pesenti, M., Noël, M.-P., Deloche, G., &amp; Cornet, J.-A. (1992). Images of numbers, or <span>“</span>when 98 is upper left and 6 sky blue<span>”</span>. <em>Cognition</em>, <em>44</em>(1), 159–196. <a href="https://doi.org/10.1016/0010-0277(92)90053-K">https://doi.org/10.1016/0010-0277(92)90053-K</a>
</div>
<div id="ref-simner2012" class="csl-entry" role="listitem">
Simner, J. (2012). Defining synaesthesia. <em>British Journal of Psychology</em>, <em>103</em>(1), 1–15. <a href="https://doi.org/10.1348/000712610X528305">https://doi.org/10.1348/000712610X528305</a>
</div>
<div id="ref-smilek2007" class="csl-entry" role="listitem">
Smilek, D., Callejas, A., Dixon, M. J., &amp; Merikle, P. M. (2007). Ovals of time: Time-space associations in synaesthesia. <em>Consciousness and Cognition</em>, <em>16</em>(2), 507–519. <a href="https://doi.org/10.1016/j.concog.2006.06.013">https://doi.org/10.1016/j.concog.2006.06.013</a>
</div>
<div id="ref-vanpetersen2020" class="csl-entry" role="listitem">
Van Petersen, E., Altgassen, M., Van Lier, R., &amp; Van Leeuwen, T. M. (2020). Enhanced spatial navigation skills in sequence-space synesthetes. <em>Cortex</em>, <em>130</em>, 49–63. <a href="https://doi.org/10.1016/j.cortex.2020.04.034">https://doi.org/10.1016/j.cortex.2020.04.034</a>
</div>
<div id="ref-ward2022a" class="csl-entry" role="listitem">
Ward, J. (2022). <em>Optimizing a measure of consistency for sequence-space synaesthesia</em>. <a href="https://osf.io/5cnr7_v1">https://osf.io/5cnr7_v1</a>
</div>
<div id="ref-ward2018" class="csl-entry" role="listitem">
Ward, J., Ipser, A., Phanvanova, E., Brown, P., Bunte, I., &amp; Simner, J. (2018). The prevalence and cognitive profile of sequence-space synaesthesia. <em>Consciousness and Cognition</em>, <em>61</em>, 79–93. <a href="https://doi.org/10.1016/j.concog.2018.03.012">https://doi.org/10.1016/j.concog.2018.03.012</a>
</div>
<div id="ref-ward2022" class="csl-entry" role="listitem">
Ward, J., &amp; Simner, J. (2022). How do Different Types of Synesthesia Cluster Together? Implications for Causal Mechanisms. <em>Perception</em>, <em>51</em>(2), 91–113. <a href="https://doi.org/10.1177/03010066211070761">https://doi.org/10.1177/03010066211070761</a>
</div>
<div id="ref-corrplot" class="csl-entry" role="listitem">
Wei, T., &amp; Simko, V. (2024). <em>R package ’<span class="nocase">corrplot</span>’: Visualization of a correlation matrix</em>. <a href="https://github.com/taiyun/corrplot">https://github.com/taiyun/corrplot</a>
</div>
<div id="ref-ggplot2" class="csl-entry" role="listitem">
Wickham, H. (2016). <em><span class="nocase">ggplot2</span>: Elegant graphics for data analysis</em>. Springer-Verlag New York. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>
</div>
<div id="ref-cowplot" class="csl-entry" role="listitem">
Wilke, C. O. (2025a). <em><span class="nocase">cowplot</span>: Streamlined plot theme and plot annotations for ’ggplot2’</em>. <a href="https://doi.org/10.32614/CRAN.package.cowplot">https://doi.org/10.32614/CRAN.package.cowplot</a>
</div>
<div id="ref-ggridges" class="csl-entry" role="listitem">
Wilke, C. O. (2025b). <em><span class="nocase">ggridges</span>: Ridgeline plots in ’ggplot2’</em>. <a href="https://doi.org/10.32614/CRAN.package.ggridges">https://doi.org/10.32614/CRAN.package.ggridges</a>
</div>
<div id="ref-youden1950" class="csl-entry" role="listitem">
Youden, W. J. (1950). Index for rating diagnostic tests. <em>Cancer</em>, <em>3</em>(1), 32–35. <a href="https://doi.org/10.1002/1097-0142(1950)3:1<32::aid-cncr2820030106>3.0.co;2-3">https://doi.org/10.1002/1097-0142(1950)3:1&lt;32::aid-cncr2820030106&gt;3.0.co;2-3</a>
</div>
</div>
<div style="page-break-after: always;"></div>
<section id="appendix" class="level3">
<h3 data-anchor-id="appendix">Appendix</h3>
<p>The additional analyses in this appendix attempt to address several concerns. Regarding the distribution’s of the scores from the different methods, i.e.&nbsp;whether it is bimodal, see <a href="#apx-featDensity" class="quarto-xref" aria-expanded="false">Appendix&nbsp;A</a>. Then to visualize the stability of the ROC analyses across the datasets, i.e. whether AUC, DP, sensitivity and specificity vary across the four different datasets, see <a href="#apx-SM2byds" class="quarto-xref" aria-expanded="false">Appendix&nbsp;B</a>.</p>
<p>To address circularity concerns that we might find methods that best classifies synesthetes and controls only from the sed on self-reported groups, we attempted two additional approaches: first, testing sub-samples based on percentiles of the questionnaire score sample distribution (see <a href="#apx-byquestperc" class="quarto-xref" aria-expanded="false">Appendix&nbsp;C</a>). The rationale is that a good consistency test should have similar discriminative performance for strong SSS and weaker SSS. To do this, we re-sampled the SSS and controls based on their questionnaire distribution by percentiles (i.e., comparing 10% highest questionnaire scores vs.&nbsp;10% lowest, then 20% vs. 20%, etc.). In addition, we correlated the questionnaire scores with the results from different features extracted from the consistency test, see <a href="#apx-correlation-with-self-report" class="quarto-xref" aria-expanded="false">Appendix&nbsp;D</a>.</p>
<p>We also wanted to visually characterize whether certain patterns occur more frequently for some categories than others (i.e.&nbsp;circular pattern for months and linear for numbers). <a href="#apx-average-forms" class="quarto-xref" aria-expanded="false">Appendix&nbsp;E</a> shows the average forms for each categories. Finally, we wanted to visualize how each participant is classified by each test. From this we found a group of Synaesthetic who consistently are classified as controls by different methods as well as a group of control who are consistently classified as synaesthetes, see <a href="#apx-alluvial" class="quarto-xref" aria-expanded="false">Appendix&nbsp;F</a>.</p>
<p>The following R packages were used for the data visualization in the appendix: ‘ggridges’ v. 0.5.7 <span class="citation" data-cites="ggridges">(<a href="#ref-ggridges" role="doc-biblioref">Wilke, 2025b</a>)</span>, ‘cowplot’ v. 1.2.0 <span class="citation" data-cites="cowplot">(<a href="#ref-cowplot" role="doc-biblioref">Wilke, 2025a</a>)</span>, ‘ggalluvial’ v. 0.12.5 <span class="citation" data-cites="ggalluvial">(<a href="#ref-ggalluvial" role="doc-biblioref">Brunson &amp; Read, 2023</a>)</span>, ‘corrplot’ v. 0.95 <span class="citation" data-cites="corrplot">(<a href="#ref-corrplot" role="doc-biblioref">Wei &amp; Simko, 2024</a>)</span></p>
</section>
</section>
<section class="level1">
<h1>Appendix A</h1>
</section>
<section id="apx-featDensity" class="level1" data-appendixtitle="A">
<h1 data-appendixtitle="A">Test’s distributions</h1>
<p>Regarding the distributions of each tests across the SSS vs.&nbsp;controls, <a href="#fig-apx01" class="quarto-xref" aria-expanded="false">Figure&nbsp;A1</a> we compared the density plots of each standardized criteria (in order to make them comparable) which visually suggests bimodal distribution.</p>
<div class="cell FigureWithNote" data-apa-note="[&quot;Red = Classified as Synesthetes, Blue =  as controls.&quot;,&quot;All method's score have been standardized (*z-score*). x axis treamed between -3 and 3 z-scores. Vertical line represent respectively 25 and 75 percentiles of each distributions.&quot;]" data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-apx01" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="A">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-apx01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;A1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Density plots of all the features comparing SSS and controls</p>
</div>
</figcaption>
<div aria-describedby="fig-apx01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-apx01-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Red&nbsp;= Classified as Synesthetes, Blue = as controls.
</div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
All method’s score have been standardized (<em>z-score</em>). x axis treamed between -3 and 3 z-scores. Vertical line represent respectively 25 and 75 percentiles of each distributions.
</div>
</div>
</section>
<section class="level1">
<h1>Appendix B</h1>
</section>
<section id="apx-SM2byds" class="level1" data-appendixtitle="B">
<h1 data-appendixtitle="B">ROC analysis by dataset</h1>
<p>Here we compare the ROC analyses results for each data sample of the three methods with the best AUC, see <a href="#fig-apx08" class="quarto-xref" aria-expanded="false">Figure&nbsp;B2</a>. Descriptively, we also looked a the distributions of each methods across SSS and controls <a href="#fig-myplotapx02" class="quarto-xref" aria-expanded="false">Figure&nbsp;B1</a>. Note that the dataset labelled as Ward 2 has more synaesthetes than controls (5:1 ratio). Note that some of the tests led to 100 % Specificity in <span class="citation" data-cites="vanpetersen2020">Van Petersen et al. (<a href="#ref-vanpetersen2020" role="doc-biblioref">2020</a>)</span> dataset.</p>
<div class="cell FigureWithNote" data-apa-note="AUC = Area Under the Curve, DP = Discrimination Power" data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-myplotapx02" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="B">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplotapx02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;B1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Lineplots of AUC and DP by data source</p>
</div>
</figcaption>
<div aria-describedby="fig-myplotapx02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplotapx02-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. AUC&nbsp;= Area Under the Curve, DP = Discrimination Power
</div>
</div>
<div class="cell FigureWithNote" data-apa-note="[&quot;Red = Classified as Synesthetes, Blue =  as controls.&quot;,&quot;All method's score have been standardized (*z-score*). x axis treamed between -3 and 3 z-scores. Vertical line indicate respectively 25 and 75 percentiles of each distributions.&quot;]" data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-apx08" class="quarto-float quarto-figure quarto-figure-center" data-fignum="2" prefix="B">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-apx08-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;B2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Density plots of all the tests comparing SSS and controls by dataset</p>
</div>
</figcaption>
<div aria-describedby="fig-apx08-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-apx08-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Red&nbsp;= Classified as Synesthetes, Blue = as controls.
</div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
All method’s score have been standardized (<em>z-score</em>). x axis treamed between -3 and 3 z-scores. Vertical line indicate respectively 25 and 75 percentiles of each distributions.
</div>
</div>
</section>
<section class="level1">
<h1>Appendix C</h1>
</section>
<section id="apx-byquestperc" class="level1" data-appendixtitle="C">
<h1 data-appendixtitle="C">ROC Analysis Sub-sampled data by questionnaire quantiles (20% steps)</h1>
<p>We compared the data sampled by the questionnaire score. Based on the distribution of the questionnaire score, we sampled the 10 % with the lowest and 10 % with the highest scores. Those are then compared with the 20 and 20 % and so on until 40 and 40 %. The rationale of this procedure is that AUC, sensitivity and specificity should remain stable across percentiles for a feature to be valid, see <a href="#fig-myplotapx03" class="quarto-xref" aria-expanded="false">Figure&nbsp;C1</a>. In other words the ROC should remain unchanged if we take extreme groups compared to less extreme ones.</p>
<div class="cell FigureWithNote" data-apa-note="Each point is an increasing percentiles. AUC = Area Under the Curve. DP = Discrimination Power. Specitficites of some tests with van Petersen data are 100 %, so the DP are nor computable nor interpretable" data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-myplotapx03" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="C">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplotapx03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;C1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Lineplots of AUC and DP by questionnaire percentile</p>
</div>
</figcaption>
<div aria-describedby="fig-myplotapx03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplotapx03-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Each&nbsp;point is an increasing percentiles. AUC = Area Under the Curve. DP = Discrimination Power. Specitficites of some tests with van Petersen data are 100 %, so the DP are nor computable nor interpretable
</div>
</div>
</section>
<section class="level1">
<h1>Appendix D</h1>
</section>
<section id="apx-correlation-with-self-report" class="level1" data-appendixtitle="D">
<h1 data-appendixtitle="D">Correlation with self-report</h1>
<p>The best criterion should also best correlate with SSS self-reported questionnaire score. Works only with Ward’s aggregated data, see <a href="#fig-myplotapx04" class="quarto-xref" aria-expanded="false">Figure&nbsp;D1</a>.</p>
<div class="cell FigureWithNote" data-apa-note="Only data from Ward is included here" data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-myplotapx04" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="D">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplotapx04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;D1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Correlation with self-reported questionnaire</p>
</div>
</figcaption>
<div aria-describedby="fig-myplotapx04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplotapx04-1.svg" class="img-fluid figure-img" width="864">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Only&nbsp;data from Ward is included here
</div>
</div>
</section>
<section class="level1">
<h1>Appendix E</h1>
</section>
<section id="apx-average-forms" class="level1" data-appendixtitle="E">
<h1 data-appendixtitle="E">Centred average forms</h1>
<p>In this additional analyses we attempted at visualizing the average for each categories to see whether a pattern could be discerned on a qualitative level. To avoid negative coordinates, we shifted all the z-scores from the whole dataset minimum for the x and y coordinates. Then we anchored to the coordinate 0,0 the stimulus “1” for numbers, “Monday” for weekdays and “January” for months. We then plotted all the space forms with transparency, see <a href="#fig-myplotapx06" class="quarto-xref" aria-expanded="false">Figure&nbsp;E1</a>.</p>
<p>Descriptively it is possible to see more circular pattern for months and horizontal and vertical patterns for numbers. Also the averaged forms appear to be more clearly defined in the synaesthetes than control.</p>
<div class="cell FigureWithoutNote" data-apa-notes="Average of all the space-forms with centers 0,0 for January, 1 and Monday respectively" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-myplotapx06" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="E">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplotapx06-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;E1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Average Centered space forms visualized</p>
</div>
</figcaption>
<div aria-describedby="fig-myplotapx06-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplotapx06-1.png" class="img-fluid figure-img" width="1950">
</div>
</figure>
</div>
</div>
</div>
</section>
<section class="level1">
<h1>Appendix F</h1>
</section>
<section id="apx-alluvial" class="level1" data-appendixtitle="F">
<h1 data-appendixtitle="F">Alluvial plot</h1>
<p>Are false positives and negatives share some characteristics? To answer this question qualitatively we identified two group of self-reported SSS participants who care consistently classified as controls by the five methods with the highest AUC (i.e.&nbsp;consistent false negatives), see dark blue lines in <a href="#fig-myplotapx07" class="quarto-xref" aria-expanded="false">Figure&nbsp;F1</a>. On the other side we identified a group of controls who are consistently classified as SSS by the five methods with the highest AUC, see dark red lines in <a href="#fig-myplotapx07" class="quarto-xref" aria-expanded="false">Figure&nbsp;F1</a> .</p>
<div class="cell FigureWithNote" data-apa-note="Red = Controls, Blue = Synaesthetes. Highlighted in blue are Synesthetes who are classified as control by all 5 tests. Highlighted in red are controls who are classified as synesthetes by all 5 tests." data-custom-style="FigureWithNote">
<div class="cell-output-display">
<div id="fig-myplotapx07" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="F">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplotapx07-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;F1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Alluvial plot of test passing</p>
</div>
</figcaption>
<div aria-describedby="fig-myplotapx07-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplotapx07-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div>
<div class="FigureNote NoIndent" data-custom-style="FigureNote">
<em>Note</em>. Red&nbsp;= Controls, Blue = Synaesthetes. Highlighted in blue are Synesthetes who are classified as control by all 5 tests. Highlighted in red are controls who are classified as synesthetes by all 5 tests.
</div>
</div>
<p>On one side 6.12 % of all participants, that is 42 Synaesthetes where consistently classified as controls by all five tests, see <a href="#fig-myplotapx08" class="quarto-xref" aria-expanded="false">Figure&nbsp;F2</a>. On the other side 3.35 % of all participants, 23 controls where consistently classified as SSS by all five tests, see <a href="#fig-myplotapx09" class="quarto-xref" aria-expanded="false">Figure&nbsp;F3</a>. Given the different approaches of each methods, the identified participants might be on one side non-genuine synesthetes and on the other controls who have SSS but are either not aware or did not identify it as such.</p>
<div class="cell FigureWithoutNote" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-myplotapx08" class="quarto-float quarto-figure quarto-figure-center" data-fignum="2" prefix="F">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplotapx08-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;F2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Synaesthetes who consistently <em>fail</em> all five tests (blue in the alluvial plot)</p>
</div>
</figcaption>
<div aria-describedby="fig-myplotapx08-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplotapx08-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<div class="cell FigureWithoutNote" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-myplotapx09" class="quarto-float quarto-figure quarto-figure-center" data-fignum="3" prefix="F">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-myplotapx09-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;F3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Controls who consistently <em>pass</em> all five tests (red in the alluvial plot)</p>
</div>
</figcaption>
<div aria-describedby="fig-myplotapx09-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2.RegisteredReport_MS2_files/figure-html/fig-myplotapx09-1.svg" class="img-fluid figure-img" width="624">
</div>
</figure>
</div>
</div>
</div>
<!--# 

# Code to visualize all spatial-forms

This exports many pdf's. It plots each ID and condition z-score x and y
coordinates. Since each coordinate is repeated 3 times, these are
represented by triangles. The line paths connect average coordinates to
visualize forms (stimulus are ordered, i.e. 1 to 9, Monday to Sunday,
January to December). Finally in the top right corner, each dots
indicates if the ID would pass (green dot) / fails (red dot) depending
on the criteria.


::: {.cell}

:::




 -->
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>